### ISSUE TITLE
Handle inbound media from Conversations

### ISSUE THREAD

**Issue by afomera** [king601/ClearManagement#3]
We should handle inbound media from twilio. 

Here's my thinking,

Twilio sends over NumMedia in params, twilio has a max of 10 media per message so it'll be in params like MediaUrl0 -> some url to the media, MediaUrl1 -> second url up to MediaUrl9 (because 0 through 9 is 10)

Right now if you just send an image and no text it'll try to create a message record, but fails because Body is blank. 

We'll probably want to rehost these images on our own server for sake of keeping them so some way of uploading the images (maybe via carrierwave? which lets us upload via url) then we can attach them to a Message ID and show them under it? like if message.has_images? loop through message.images.each

and display thumbnails of the images, letting you click on them for a lightbox view of the images uploaded.

**Comment by afomera** [comment]
We also need to issue an HTTP DELETE request to Twilio to delete the images from Twilio so we aren't charged for them

**Comment by afomera** [comment]
https://www.twilio.com/docs/api/rest/media <-- twilios docs

**Comment by ChristopherCLee** [comment]
Do you need to test for the mime type of the resource?

https://github.com/mime-types/ruby-mime-types

**Comment by afomera** [comment]
shouldnt. The Twilio Ruby gem allows me to check the content type I believe so if it's an image I'll just check for that, not sure if I care about what other kinds of media there is
